// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NHLStats.Domain;

#nullable disable

namespace NHLStats.Domain.Migrations
{
    [DbContext(typeof(NhlStatsDbContext))]
    [Migration("20260308160347_AddRolesAndLoginUserLink")]
    partial class AddRolesAndLoginUserLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId", "MatchNumber")
                        .IsUnique();

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.MoneyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NegativePointValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PositivePointValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MoneyConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EffectiveFrom = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NegativePointValue = 0.50m,
                            PositivePointValue = 0.25m
                        });
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.PointReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PointReasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            IsPositive = false,
                            Name = "Penalty"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            IsPositive = false,
                            Name = "Secondary Penalty"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            IsPositive = false,
                            Name = "Not Scoring A Goal"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            IsPositive = false,
                            Name = "Scoring 10 Goals"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            IsPositive = false,
                            Name = "Last Minute Action"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            IsPositive = false,
                            Name = "Own Goal"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            IsPositive = false,
                            Name = "Error In Defense"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            IsPositive = false,
                            Name = "Prediction"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            IsPositive = true,
                            Name = "Penalty"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            IsPositive = true,
                            Name = "Secondary Penalty"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            IsPositive = true,
                            Name = "Not Scoring A Goal"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            IsPositive = true,
                            Name = "Scoring 10 Goals"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            IsPositive = true,
                            Name = "Last Minute Action"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            IsPositive = true,
                            Name = "Own Goal"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            IsPositive = true,
                            Name = "Error In Defense"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            IsPositive = true,
                            Name = "Prediction"
                        });
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.RosterPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.ToTable("RosterPlayers");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HostedTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HostedTeamId");

                    b.HasIndex("ParentSeasonId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.SeasonUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SeasonId", "UserId")
                        .IsUnique();

                    b.ToTable("SeasonUsers");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Anaheim Ducks",
                            ShortName = "ANA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Arizona Coyotes",
                            ShortName = "ARI"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Boston Bruins",
                            ShortName = "BOS"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Buffalo Sabres",
                            ShortName = "BUF"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Calgary Flames",
                            ShortName = "CGY"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Carolina Hurricanes",
                            ShortName = "CAR"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Chicago Blackhawks",
                            ShortName = "CHI"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Colorado Avalanche",
                            ShortName = "COL"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Columbus Blue Jackets",
                            ShortName = "CBJ"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Dallas Stars",
                            ShortName = "DAL"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Detroit Red Wings",
                            ShortName = "DET"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Edmonton Oilers",
                            ShortName = "EDM"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Florida Panthers",
                            ShortName = "FLA"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Los Angeles Kings",
                            ShortName = "LAK"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Minnesota Wild",
                            ShortName = "MIN"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Montréal Canadiens",
                            ShortName = "MTL"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Nashville Predators",
                            ShortName = "NSH"
                        },
                        new
                        {
                            Id = 18,
                            Name = "New Jersey Devils",
                            ShortName = "NJD"
                        },
                        new
                        {
                            Id = 19,
                            Name = "New York Islanders",
                            ShortName = "NYI"
                        },
                        new
                        {
                            Id = 20,
                            Name = "New York Rangers",
                            ShortName = "NYR"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Ottawa Senators",
                            ShortName = "OTT"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Philadelphia Flyers",
                            ShortName = "PHI"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Pittsburgh Penguins",
                            ShortName = "PIT"
                        },
                        new
                        {
                            Id = 24,
                            Name = "San Jose Sharks",
                            ShortName = "SJS"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Seattle Kraken",
                            ShortName = "SEA"
                        },
                        new
                        {
                            Id = 26,
                            Name = "St. Louis Blues",
                            ShortName = "STL"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Tampa Bay Lightning",
                            ShortName = "TBL"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Toronto Maple Leafs",
                            ShortName = "TOR"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Vancouver Canucks",
                            ShortName = "VAN"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Vegas Golden Knights",
                            ShortName = "VGK"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Washington Capitals",
                            ShortName = "WSH"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Winnipeg Jets",
                            ShortName = "WPG"
                        });
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.UserMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMatches");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.UserMatchGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RosterPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserMatchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RosterPlayerId");

                    b.HasIndex("UserMatchId");

                    b.ToTable("UserMatchGoals");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.UserMatchPenalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RosterPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserMatchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RosterPlayerId");

                    b.HasIndex("UserMatchId");

                    b.ToTable("UserMatchPenalties");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.UserMatchPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointReasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserMatchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PointReasonId");

                    b.HasIndex("UserMatchId");

                    b.ToTable("UserMatchPoints");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.UserPayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaidOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPayouts");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.UserSeasonAggregatedData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMinus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPlus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("UserId", "SeasonId")
                        .IsUnique();

                    b.ToTable("UserSeasonAggregatedData");
                });

            modelBuilder.Entity("NHLStats.Domain.Identity.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AppRoles", (string)null);
                });

            modelBuilder.Entity("NHLStats.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NHLStats.Domain.Identity.LoginRoleRelation", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("LoginRoleRelations", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("NHLStats.Domain.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NHLStats.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NHLStats.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NHLStats.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.Match", b =>
                {
                    b.HasOne("NHLStats.Domain.Entities.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NHLStats.Domain.Entities.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NHLStats.Domain.Entities.Season", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.RosterPlayer", b =>
                {
                    b.HasOne("NHLStats.Domain.Entities.Season", "Season")
                        .WithMany("RosterPlayers")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NHLStats.Domain.Entities.Team", "Team")
                        .WithMany("RosterPlayers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.Season", b =>
                {
                    b.HasOne("NHLStats.Domain.Entities.Team", "HostedTeam")
                        .WithMany()
                        .HasForeignKey("HostedTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NHLStats.Domain.Entities.Season", "ParentSeason")
                        .WithMany()
                        .HasForeignKey("ParentSeasonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HostedTeam");

                    b.Navigation("ParentSeason");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.SeasonUser", b =>
                {
                    b.HasOne("NHLStats.Domain.Entities.Season", "Season")
                        .WithMany("SeasonUsers")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NHLStats.Domain.Entities.User", "User")
                        .WithMany("SeasonUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.UserMatch", b =>
                {
                    b.HasOne("NHLStats.Domain.Entities.Match", "Match")
                        .WithMany("UserMatches")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NHLStats.Domain.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NHLStats.Domain.Entities.User", "User")
                        .WithMany("UserMatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.UserMatchGoal", b =>
                {
                    b.HasOne("NHLStats.Domain.Entities.RosterPlayer", "RosterPlayer")
                        .WithMany()
                        .HasForeignKey("RosterPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NHLStats.Domain.Entities.UserMatch", "UserMatch")
                        .WithMany("Goals")
                        .HasForeignKey("UserMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RosterPlayer");

                    b.Navigation("UserMatch");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.UserMatchPenalty", b =>
                {
                    b.HasOne("NHLStats.Domain.Entities.RosterPlayer", "RosterPlayer")
                        .WithMany()
                        .HasForeignKey("RosterPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NHLStats.Domain.Entities.UserMatch", "UserMatch")
                        .WithMany("Penalties")
                        .HasForeignKey("UserMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RosterPlayer");

                    b.Navigation("UserMatch");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.UserMatchPoint", b =>
                {
                    b.HasOne("NHLStats.Domain.Entities.PointReason", "PointReason")
                        .WithMany()
                        .HasForeignKey("PointReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NHLStats.Domain.Entities.UserMatch", "UserMatch")
                        .WithMany("Points")
                        .HasForeignKey("UserMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PointReason");

                    b.Navigation("UserMatch");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.UserPayout", b =>
                {
                    b.HasOne("NHLStats.Domain.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NHLStats.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.UserSeasonAggregatedData", b =>
                {
                    b.HasOne("NHLStats.Domain.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NHLStats.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NHLStats.Domain.Identity.ApplicationUser", b =>
                {
                    b.HasOne("NHLStats.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NHLStats.Domain.Identity.LoginRoleRelation", b =>
                {
                    b.HasOne("NHLStats.Domain.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NHLStats.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.Match", b =>
                {
                    b.Navigation("UserMatches");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.Season", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("RosterPlayers");

                    b.Navigation("SeasonUsers");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");

                    b.Navigation("RosterPlayers");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.User", b =>
                {
                    b.Navigation("SeasonUsers");

                    b.Navigation("UserMatches");
                });

            modelBuilder.Entity("NHLStats.Domain.Entities.UserMatch", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Penalties");

                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
