export interface AchievementDef {
    id:           string
    levelIcons:   readonly [string, string, string, string, string, string, string]
    levelNames:   readonly [string, string, string, string, string, string, string]
    descKey:      string
    valueLabel:   string
    disabledIcon?: string
}

const ICONS: readonly [string, string, string, string, string, string, string] =
    ['?', '?', '?', '?', '?', '?', '?']

export const ACHIEVEMENT_DEFS: AchievementDef[] = [
    {
        id: 'sniper',
        levelIcons: [
            '/achievements/sniper/sniper-stone.png',
            '/achievements/sniper/sniper-bronze.png',
            '/achievements/sniper/sniper-silver.png',
            '/achievements/sniper/sniper-gold.png',
            '/achievements/sniper/sniper-emerald.png',
            '/achievements/sniper/sniper-ruby.png',
            '/achievements/sniper/sniper-diamond.png',
        ],
        disabledIcon: '/achievements/sniper/sniper-disabled.png',
        levelNames: ['Shooter', 'Marksman', 'Sniper', 'Artillery', 'Executioner', 'Annihilator', 'One-Man Army'],
        descKey: 'achievements.sniper.desc',
        valueLabel: 'goals',
    },
    {
        id: 'domination',
        levelIcons: [
            '/achievements/domination/domination-stone.png',
            '/achievements/domination/domination-bronze.png',
            '/achievements/domination/domination-silver.png',
            '/achievements/domination/domination-gold.png',
            '/achievements/domination/domination-emerald.png',
            '/achievements/domination/domination-ruby.png',
            '/achievements/domination/domination-diamond.png',
        ],
        disabledIcon: '/achievements/domination/domination-disabled.png',
        levelNames: ['Press', 'Siege', 'Onslaught', 'Domination', 'Blitzkrieg', 'Juggernaut', 'Unstoppable Force'],
        descKey: 'achievements.domination.desc',
        valueLabel: 'goals',
    },
    {
        id: 'shorty',
        levelIcons: [
            '/achievements/shorty/shorty-stone.png',
            '/achievements/shorty/shorty-bronze.png',
            '/achievements/shorty/shorty-silver.png',
            '/achievements/shorty/shorty-gold.png',
            '/achievements/shorty/shorty-emerald.png',
            '/achievements/shorty/shorty-ruby.png',
            '/achievements/shorty/shorty-diamond.png',
        ],
        disabledIcon: '/achievements/shorty/shorty-disabled.png',
        levelNames: ['Pickpocket', 'Thief', 'Bandit', 'Shorty', 'Assassin', 'Shorthanded God', 'Ghost Roster'],
        descKey: 'achievements.shorty.desc',
        valueLabel: 'SH goals',
    },
    {
        id: 'god_mode',
        levelIcons: [
            '/achievements/godmode/god-stone.png',
            '/achievements/godmode/god-bronze.png',
            '/achievements/godmode/god-silver.png',
            '/achievements/godmode/god-gold.png',
            '/achievements/godmode/god-emerald.png',
            '/achievements/godmode/god-ruby.png',
            '/achievements/godmode/god-diamond.png',
        ],
        disabledIcon: '/achievements/godmode/god-disabled.png',
        levelNames: ['Hot Hands', 'Firestorm', 'Goal Machine', 'God Mode', 'Offensive Deity', 'Hockey Olympus', 'Immortal Lineup'],
        descKey: 'achievements.godMode.desc',
        valueLabel: 'fwd goals',
    },
    {
        id: 'blue_line_snipers',
        levelIcons: [
            '/achievements/bluelinesniper/blue-stone.png',
            '/achievements/bluelinesniper/blue-bronze.png',
            '/achievements/bluelinesniper/blue-silver.png',
            '/achievements/bluelinesniper/blue-gold.png',
            '/achievements/bluelinesniper/blue-emerald.png',
            '/achievements/bluelinesniper/blue-ruby.png',
            '/achievements/bluelinesniper/blue-diamond.png',
        ],
        disabledIcon: '/achievements/bluelinesniper/blue-disabled.png',
        levelNames: ['Point Shot', 'Blue Line Threat', 'Slapshot King', 'Blue Line Snipers', 'Heavy Artillery', 'Howitzer', 'Defensive Dynasty'],
        descKey: 'achievements.blueLineSnipers.desc',
        valueLabel: 'def goals',
    },
    {
        id: 'massive_attack',
        levelIcons: [
            '/achievements/massiveattack/massive-stone.png',
            '/achievements/massiveattack/massive-bronze.png',
            '/achievements/massiveattack/massive-silver.png',
            '/achievements/massiveattack/massive-gold.png',
            '/achievements/massiveattack/massive-emerald.png',
            '/achievements/massiveattack/massive-ruby.png',
            '/achievements/massiveattack/massive-diamond.png',
        ],
        disabledIcon: '/achievements/massiveattack/massive-disabled.png',
        levelNames: ['Offense', 'Wave', 'Surge', 'Massive Attack', 'Avalanche', 'Tsunami', 'Doomsday'],
        descKey: 'achievements.massiveAttack.desc',
        valueLabel: 'fwd goals',
    },
    {
        id: 'offensive_defenseman',
        levelIcons: [
            '/achievements/offensivedefenseman/defenseman-stone.png',
            '/achievements/offensivedefenseman/defenseman-bronze.png',
            '/achievements/offensivedefenseman/defenseman-silver.png',
            '/achievements/offensivedefenseman/defenseman-gold.png',
            '/achievements/offensivedefenseman/defenseman-emerald.png',
            '/achievements/offensivedefenseman/defenseman-ruby.png',
            '/achievements/offensivedefenseman/defenseman-diamond.png',
        ],
        disabledIcon: '/achievements/offensivedefenseman/defenseman-disabled.png',
        levelNames: ['Two-Way', 'Puck Mover', 'Rover', 'Offensive Defenseman', 'Fourth Forward', 'Blue Line General', 'Bobby Orr Reincarnate'],
        descKey: 'achievements.offensiveDefenseman.desc',
        valueLabel: 'def goals',
    },
    {
        id: 'player_lover',
        levelIcons: [
            '/achievements/playerlover/lover-stone.png',
            '/achievements/playerlover/lover-bronze.png',
            '/achievements/playerlover/lover-silver.png',
            '/achievements/playerlover/lover-gold.png',
            '/achievements/playerlover/lover-emerald.png',
            '/achievements/playerlover/lover-ruby.png',
            '/achievements/playerlover/lover-diamond.png',
        ],
        disabledIcon: '/achievements/playerlover/lover-disabled.png',
        levelNames: ['Target', 'Favorite', 'Muse', 'Player Lover', 'Obsession', 'Cult of Personality', 'One-Man Franchise'],
        descKey: 'achievements.playerLover.desc',
        valueLabel: 'goals',
    },
    {
        id: 'golden_stick',
        levelIcons: [
            '/achievements/goldenstick/stick-stone.png',
            '/achievements/goldenstick/stick-bronze.png',
            '/achievements/goldenstick/stick-silver.png',
            '/achievements/goldenstick/stick-gold.png',
            '/achievements/goldenstick/stick-emerald.png',
            '/achievements/goldenstick/stick-ruby.png',
            '/achievements/goldenstick/stick-diamond.png',
        ],
        disabledIcon: '/achievements/goldenstick/stick-disabled.png',
        levelNames: ['Top Scorer', 'Golden Stick', 'Goal Magnet', 'Rocket Richard', 'The Great One', 'Scoring Legend', 'Hockey God'],
        descKey: 'achievements.goldenStick.desc',
        valueLabel: 'goals',
    },
    {
        id: 'sin_bin_vip',
        levelIcons: [
            '/achievements/sinbinvip/sinbin-stone.png',
            '/achievements/sinbinvip/sinbin-bronze.png',
            '/achievements/sinbinvip/sinbin-silver.png',
            '/achievements/sinbinvip/sinbin-gold.png',
            '/achievements/sinbinvip/sinbin-emerald.png',
            '/achievements/sinbinvip/sinbin-ruby.png',
            '/achievements/sinbinvip/sinbin-diamond.png',
        ],
        disabledIcon: '/achievements/sinbinvip/sinbin-disabled.png',
        levelNames: ['Troublemaker', 'Regular Guest', 'Brawler', 'Sin Bin VIP', 'Mayor of the Box', 'Lifetime Membership', 'Solitary Confinement'],
        descKey: 'achievements.sinBinVip.desc',
        valueLabel: 'penalties',
    },
    {
        id: 'broad_street_bully',
        levelIcons: [
            '/achievements/broadstreetbully/bully-stone.png',
            '/achievements/broadstreetbully/bully-bronze.png',
            '/achievements/broadstreetbully/bully-silver.png',
            '/achievements/broadstreetbully/bully-gold.png',
            '/achievements/broadstreetbully/bully-emerald.png',
            '/achievements/broadstreetbully/bully-ruby.png',
            '/achievements/broadstreetbully/bully-diamond.png',
        ],
        disabledIcon: '/achievements/broadstreetbully/bully-disabled.png',
        levelNames: ['Gritty', 'Tough Guys', 'Ruffians', 'Broad Street Bully', 'Fight Club', 'Prison Yard', 'Legion of Doom'],
        descKey: 'achievements.broadStreetBully.desc',
        valueLabel: 'penalties',
    },
    {
        id: 'disciplinary_hearing',
        levelIcons: [
            '/achievements/disciplinaryhearing/disciplinary-stone.png',
            '/achievements/disciplinaryhearing/disciplinary-bronze.png',
            '/achievements/disciplinaryhearing/disciplinary-silver.png',
            '/achievements/disciplinaryhearing/disciplinary-gold.png',
            '/achievements/disciplinaryhearing/disciplinary-emerald.png',
            '/achievements/disciplinaryhearing/disciplinary-ruby.png',
            '/achievements/disciplinaryhearing/disciplinary-diamond.png',
        ],
        disabledIcon: '/achievements/disciplinaryhearing/disciplinary-disabled.png',
        levelNames: ['Warning', 'Fine', 'Misconduct', 'Disciplinary Hearing', 'Suspended', 'Blacklisted', 'Banned for Life'],
        descKey: 'achievements.disciplinaryHearing.desc',
        valueLabel: 'penalties',
    },
    {
        id: 'the_enforcer',
        levelIcons: [
            '/achievements/theenforcer/enforcer-stone.png',
            '/achievements/theenforcer/enforcer-bronze.png',
            '/achievements/theenforcer/enforcer-silver.png',
            '/achievements/theenforcer/enforcer-gold.png',
            '/achievements/theenforcer/enforcer-emerald.png',
            '/achievements/theenforcer/enforcer-ruby.png',
            '/achievements/theenforcer/enforcer-diamond.png',
        ],
        disabledIcon: '/achievements/theenforcer/enforcer-disabled.png',
        levelNames: ['Agitator', 'Pest', 'Bruiser', 'The Enforcer', 'Hitman', 'The Terminator', 'The Undertaker'],
        descKey: 'achievements.theEnforcer.desc',
        valueLabel: 'penalties',
    },
    {
        id: 'goon_squad',
        levelIcons: [
            '/achievements/goonsquad/goon-stone.png',
            '/achievements/goonsquad/goon-bronze.png',
            '/achievements/goonsquad/goon-silver.png',
            '/achievements/goonsquad/goon-gold.png',
            '/achievements/goonsquad/goon-emerald.png',
            '/achievements/goonsquad/goon-ruby.png',
            '/achievements/goonsquad/goon-diamond.png',
        ],
        disabledIcon: '/achievements/goonsquad/goon-disabled.png',
        levelNames: ['Bad Boys', 'Dirty Roster', 'Criminals', 'Goon Squad', 'The Mob', 'Cartel', 'Most Wanted'],
        descKey: 'achievements.goonSquad.desc',
        valueLabel: 'penalties',
    },
    {
        id: 'jailbird',
        levelIcons: [
            '/achievements/jailbird/jailbird-stone.png',
            '/achievements/jailbird/jailbird-bronze.png',
            '/achievements/jailbird/jailbird-silver.png',
            '/achievements/jailbird/jailbird-gold.png',
            '/achievements/jailbird/jailbird-emerald.png',
            '/achievements/jailbird/jailbird-ruby.png',
            '/achievements/jailbird/jailbird-diamond.png',
        ],
        disabledIcon: '/achievements/jailbird/jailbird-disabled.png',
        levelNames: ['Villain', 'Nuisance', 'Menace', 'Public Enemy', 'Terror of the Rink', 'Wanted Dead or Alive', 'Enemy of the State'],
        descKey: 'achievements.jailbird.desc',
        valueLabel: 'penalties',
    },
    {
        id: 'unlucky',
        levelIcons: [
            '/achievements/unlucky/unlucky-stone.png',
            '/achievements/unlucky/unlucky-bronze.png',
            '/achievements/unlucky/unlucky-silver.png',
            '/achievements/unlucky/unlucky-gold.png',
            '/achievements/unlucky/unlucky-emerald.png',
            '/achievements/unlucky/unlucky-ruby.png',
            '/achievements/unlucky/unlucky-diamond.png',
        ],
        disabledIcon: '/achievements/unlucky/unlucky-disabled.png',
        levelNames: ['Off Day', 'Slump', 'Cursed', 'Unlucky', 'Tragedy', 'Walking Disaster', 'Black Cat'],
        descKey: 'achievements.unlucky.desc',
        valueLabel: 'minus',
    },
    {
        id: 'deep_pockets',
        levelIcons: [
            '/achievements/deeppockets/pocket-stone.png',
            '/achievements/deeppockets/pocket-bronze.png',
            '/achievements/deeppockets/pocket-silver.png',
            '/achievements/deeppockets/pocket-gold.png',
            '/achievements/deeppockets/pocket-emerald.png',
            '/achievements/deeppockets/pocket-ruby.png',
            '/achievements/deeppockets/pocket-diamond.png',
        ],
        disabledIcon: '/achievements/deeppockets/pocket-disable.png',
        levelNames: ['Coin Tosser', 'Payer', 'Contributor', 'Deep Pockets', 'Cash Cow', 'Sugar Daddy', 'The Federal Reserve'],
        descKey: 'achievements.deepPockets.desc',
        valueLabel: 'minus',
    },
    {
        id: 'vip_sponzor',
        levelIcons: [
            '/achievements/vipsponsor/sponsor-stone.png',
            '/achievements/vipsponsor/sponsor-bronze.png',
            '/achievements/vipsponsor/sponzor-silver.png',
            '/achievements/vipsponsor/sponzor-gold.png',
            '/achievements/vipsponsor/sponzor-emerald.png',
            '/achievements/vipsponsor/sponzor-ruby.png',
            '/achievements/vipsponsor/sponzor-diamond.png',
        ],
        disabledIcon: '/achievements/vipsponsor/sponsor-disabled.png',
        levelNames: ['Funder', 'Investor', 'Patron', 'VIP Sponzor', 'Philanthropist', 'Club Owner', 'Infinite Wallet'],
        descKey: 'achievements.vipSponzor.desc',
        valueLabel: 'minus',
    },
    {
        id: 'the_atm',
        levelIcons: [
            '/achievements/theatm/atm-stone.png',
            '/achievements/theatm/atm-bronze.png',
            '/achievements/theatm/atm-silver.png',
            '/achievements/theatm/atm-gold.png',
            '/achievements/theatm/atm-emerald.png',
            '/achievements/theatm/atm-ruby.png',
            '/achievements/theatm/atm-diamond.png',
        ],
        disabledIcon: '/achievements/theatm/atm-disabled.png',
        levelNames: ['Wallet', 'ATM', 'Gold Mine', 'Generálny Sponzor', 'Central Bank', 'The Treasury', 'Ekonomický Pilier'],
        descKey: 'achievements.theAtm.desc',
        valueLabel: 'minus',
    },
    {
        id: 'ice_general',
        levelIcons: [
            '/achievements/icegeneral/general-stone.png',
            '/achievements/icegeneral/general-bronze.png',
            '/achievements/icegeneral/general-silver.png',
            '/achievements/icegeneral/general-gold.png',
            '/achievements/icegeneral/general-emerald.png',
            '/achievements/icegeneral/general-ruby.png',
            '/achievements/icegeneral/general-diamond.png',
        ],
        disabledIcon: '/achievements/icegeneral/general-disabled.png',
        levelNames: ['Tactician', 'Commander', 'Leader', 'Ice General', 'Mastermind', 'Emperor', 'Hockey Dictator'],
        descKey: 'achievements.iceGeneral.desc',
        valueLabel: 'plus',
    },
    {
        id: 'good_week',
        levelIcons: [
            '/achievements/goodweek/week-stone.png',
            '/achievements/goodweek/week-bronze.png',
            '/achievements/goodweek/week-silver.png',
            '/achievements/goodweek/week-gold.png',
            '/achievements/goodweek/week-emerald.png',
            '/achievements/goodweek/week-ruby.png',
            '/achievements/goodweek/week-diamond.png',
        ],
        disabledIcon: '/achievements/goodweek/week-disabled.png',
        levelNames: ['Decent', 'In the Zone', 'On Fire', 'Good Week', 'Perfect Run', 'Flawless', 'Legendary Streak'],
        descKey: 'achievements.goodWeek.desc',
        valueLabel: 'plus',
    },
    {
        id: 'happy_season',
        levelIcons: ICONS,
        levelNames: ['Solid Run', 'Great Form', 'Dominant', 'Happy Season', 'Dream Year', 'Historic Run', 'Hall of Fame Season'],
        descKey: 'achievements.happySeason.desc',
        valueLabel: 'plus',
    },
    {
        id: 'king_of_the_rink',
        levelIcons: ICONS,
        levelNames: ['Star', 'Superstar', 'Franchise Player', 'MVP', 'The King', 'G.O.A.T.', 'Hockey Messiah'],
        descKey: 'achievements.kingOfTheRink.desc',
        valueLabel: 'plus',
    },
    {
        id: 'oracle',
        levelIcons: ICONS,
        levelNames: ['Guesser', 'Fortune Teller', 'Psychic', 'Oracle', 'Seer', 'Time Traveler', 'All-Knowing'],
        descKey: 'achievements.oracle.desc',
        valueLabel: '€ stake',
    },
    {
        id: 'the_bookie',
        levelIcons: [
            '/achievements/bookie/bookie-stone.png',
            '/achievements/bookie/bookie-bronze.png',
            '/achievements/bookie/bookie-silver.png',
            '/achievements/bookie/bookie-gold.png',
            '/achievements/bookie/bookie-emerald.png',
            '/achievements/bookie/bookie-ruby.png',
            '/achievements/bookie/bookie-diamond.png',
        ],
        disabledIcon: '/achievements/bookie/bookie-disabled.png',
        levelNames: ['Gambler', 'Hustler', 'Shark', 'The Bookie', 'Casino Boss', 'The House', 'Syndicate Leader'],
        descKey: 'achievements.theBookie.desc',
        valueLabel: 'wins',
    },
    {
        id: 'nostradamus',
        levelIcons: ICONS,
        levelNames: ['Risky', 'High Roller', 'Visionary', 'Nostradamus', 'Prophet', 'The Matrix', 'Reality Bender'],
        descKey: 'achievements.nostradamus.desc',
        valueLabel: '€ stake',
    },
    {
        id: 'swiss_army_knife',
        levelIcons: ICONS,
        levelNames: ['Handy', 'Utility', 'All-Rounder', 'Swiss Army Knife', 'Jack of All Trades', 'The Maestro', 'Ultimate Weapon'],
        descKey: 'achievements.swissArmyKnife.desc',
        valueLabel: '',
    },
]
