export interface AchievementDef {
    id:           string
    levelIcons:   readonly [string, string, string, string, string, string, string]
    levelNames:   readonly [string, string, string, string, string, string, string]
    descKey:      string
    valueLabel:   string
    disabledIcon?: string
}

const ICONS: readonly [string, string, string, string, string, string, string] =
    ['?', '?', '?', '?', '?', '?', '?']

export const ACHIEVEMENT_DEFS: AchievementDef[] = [
    {
        id: 'sniper',
        levelIcons: [
            '/achievements/sniper/sniper-stone.png',
            '/achievements/sniper/sniper-bronze.png',
            '/achievements/sniper/sniper-silver.png',
            '/achievements/sniper/sniper-gold.png',
            '/achievements/sniper/sniper-emerald.png',
            '/achievements/sniper/sniper-ruby.png',
            '/achievements/sniper/sniper-diamond.png',
        ],
        disabledIcon: '/achievements/sniper/sniper-disabled.png',
        levelNames: ['Shooter', 'Marksman', 'Sniper', 'Artillery', 'Executioner', 'Annihilator', 'One-Man Army'],
        descKey: 'achievements.sniper.desc',
        valueLabel: 'goals',
    },
    {
        id: 'domination',
        levelIcons: ICONS,
        levelNames: ['Press', 'Siege', 'Onslaught', 'Domination', 'Blitzkrieg', 'Juggernaut', 'Unstoppable Force'],
        descKey: 'achievements.domination.desc',
        valueLabel: 'goals',
    },
    {
        id: 'shorty',
        levelIcons: ICONS,
        levelNames: ['Pickpocket', 'Thief', 'Bandit', 'Shorty', 'Assassin', 'Shorthanded God', 'Ghost Roster'],
        descKey: 'achievements.shorty.desc',
        valueLabel: 'SH goals',
    },
    {
        id: 'god_mode',
        levelIcons: ICONS,
        levelNames: ['Hot Hands', 'Firestorm', 'Goal Machine', 'God Mode', 'Offensive Deity', 'Hockey Olympus', 'Immortal Lineup'],
        descKey: 'achievements.godMode.desc',
        valueLabel: 'fwd goals',
    },
    {
        id: 'blue_line_snipers',
        levelIcons: ICONS,
        levelNames: ['Point Shot', 'Blue Line Threat', 'Slapshot King', 'Blue Line Snipers', 'Heavy Artillery', 'Howitzer', 'Defensive Dynasty'],
        descKey: 'achievements.blueLineSnipers.desc',
        valueLabel: 'def goals',
    },
    {
        id: 'massive_attack',
        levelIcons: ICONS,
        levelNames: ['Offense', 'Wave', 'Surge', 'Massive Attack', 'Avalanche', 'Tsunami', 'Doomsday'],
        descKey: 'achievements.massiveAttack.desc',
        valueLabel: 'fwd goals',
    },
    {
        id: 'offensive_defenseman',
        levelIcons: ICONS,
        levelNames: ['Two-Way', 'Puck Mover', 'Rover', 'Offensive Defenseman', 'Fourth Forward', 'Blue Line General', 'Bobby Orr Reincarnate'],
        descKey: 'achievements.offensiveDefenseman.desc',
        valueLabel: 'def goals',
    },
    {
        id: 'player_lover',
        levelIcons: ICONS,
        levelNames: ['Target', 'Favorite', 'Muse', 'Player Lover', 'Obsession', 'Cult of Personality', 'One-Man Franchise'],
        descKey: 'achievements.playerLover.desc',
        valueLabel: 'goals',
    },
    {
        id: 'golden_stick',
        levelIcons: ICONS,
        levelNames: ['Top Scorer', 'Golden Stick', 'Goal Magnet', 'Rocket Richard', 'The Great One', 'Scoring Legend', 'Hockey God'],
        descKey: 'achievements.goldenStick.desc',
        valueLabel: 'goals',
    },
    {
        id: 'sin_bin_vip',
        levelIcons: ICONS,
        levelNames: ['Troublemaker', 'Regular Guest', 'Brawler', 'Sin Bin VIP', 'Mayor of the Box', 'Lifetime Membership', 'Solitary Confinement'],
        descKey: 'achievements.sinBinVip.desc',
        valueLabel: 'penalties',
    },
    {
        id: 'broad_street_bully',
        levelIcons: ICONS,
        levelNames: ['Gritty', 'Tough Guys', 'Ruffians', 'Broad Street Bully', 'Fight Club', 'Prison Yard', 'Legion of Doom'],
        descKey: 'achievements.broadStreetBully.desc',
        valueLabel: 'penalties',
    },
    {
        id: 'disciplinary_hearing',
        levelIcons: ICONS,
        levelNames: ['Warning', 'Fine', 'Misconduct', 'Disciplinary Hearing', 'Suspended', 'Blacklisted', 'Banned for Life'],
        descKey: 'achievements.disciplinaryHearing.desc',
        valueLabel: 'penalties',
    },
    {
        id: 'the_enforcer',
        levelIcons: ICONS,
        levelNames: ['Agitator', 'Pest', 'Bruiser', 'The Enforcer', 'Hitman', 'The Terminator', 'The Undertaker'],
        descKey: 'achievements.theEnforcer.desc',
        valueLabel: 'penalties',
    },
    {
        id: 'goon_squad',
        levelIcons: ICONS,
        levelNames: ['Bad Boys', 'Dirty Roster', 'Criminals', 'Goon Squad', 'The Mob', 'Cartel', 'Most Wanted'],
        descKey: 'achievements.goonSquad.desc',
        valueLabel: 'penalties',
    },
    {
        id: 'jailbird',
        levelIcons: ICONS,
        levelNames: ['Villain', 'Nuisance', 'Menace', 'Public Enemy', 'Terror of the Rink', 'Wanted Dead or Alive', 'Enemy of the State'],
        descKey: 'achievements.jailbird.desc',
        valueLabel: 'penalties',
    },
    {
        id: 'unlucky',
        levelIcons: ICONS,
        levelNames: ['Off Day', 'Slump', 'Cursed', 'Unlucky', 'Tragedy', 'Walking Disaster', 'Black Cat'],
        descKey: 'achievements.unlucky.desc',
        valueLabel: 'minus',
    },
    {
        id: 'deep_pockets',
        levelIcons: ICONS,
        levelNames: ['Coin Tosser', 'Payer', 'Contributor', 'Deep Pockets', 'Cash Cow', 'Sugar Daddy', 'The Federal Reserve'],
        descKey: 'achievements.deepPockets.desc',
        valueLabel: 'minus',
    },
    {
        id: 'vip_sponzor',
        levelIcons: ICONS,
        levelNames: ['Funder', 'Investor', 'Patron', 'VIP Sponzor', 'Philanthropist', 'Club Owner', 'Infinite Wallet'],
        descKey: 'achievements.vipSponzor.desc',
        valueLabel: 'minus',
    },
    {
        id: 'the_atm',
        levelIcons: ICONS,
        levelNames: ['Wallet', 'ATM', 'Gold Mine', 'Generálny Sponzor', 'Central Bank', 'The Treasury', 'Ekonomický Pilier'],
        descKey: 'achievements.theAtm.desc',
        valueLabel: 'minus',
    },
    {
        id: 'ice_general',
        levelIcons: ICONS,
        levelNames: ['Tactician', 'Commander', 'Leader', 'Ice General', 'Mastermind', 'Emperor', 'Hockey Dictator'],
        descKey: 'achievements.iceGeneral.desc',
        valueLabel: 'plus',
    },
    {
        id: 'good_week',
        levelIcons: ICONS,
        levelNames: ['Decent', 'In the Zone', 'On Fire', 'Good Week', 'Perfect Run', 'Flawless', 'Legendary Streak'],
        descKey: 'achievements.goodWeek.desc',
        valueLabel: 'plus',
    },
    {
        id: 'happy_season',
        levelIcons: ICONS,
        levelNames: ['Solid Run', 'Great Form', 'Dominant', 'Happy Season', 'Dream Year', 'Historic Run', 'Hall of Fame Season'],
        descKey: 'achievements.happySeason.desc',
        valueLabel: 'plus',
    },
    {
        id: 'king_of_the_rnk',
        levelIcons: ICONS,
        levelNames: ['Star', 'Superstar', 'Franchise Player', 'MVP', 'The King', 'G.O.A.T.', 'Hockey Messiah'],
        descKey: 'achievements.kingOfTheRnk.desc',
        valueLabel: 'plus',
    },
    {
        id: 'oracle',
        levelIcons: ICONS,
        levelNames: ['Guesser', 'Fortune Teller', 'Psychic', 'Oracle', 'Seer', 'Time Traveler', 'All-Knowing'],
        descKey: 'achievements.oracle.desc',
        valueLabel: '€ stake',
    },
    {
        id: 'the_bookie',
        levelIcons: [
            '/achievements/bookie/bookie-stone.png',
            '/achievements/bookie/bookie-bronze.png',
            '/achievements/bookie/bookie-silver.png',
            '/achievements/bookie/bookie-gold.png',
            '/achievements/bookie/bookie-emerald.png',
            '/achievements/bookie/bookie-ruby.png',
            '/achievements/bookie/bookie-diamond.png',
        ],
        disabledIcon: '/achievements/bookie/bookie-disabled.png',
        levelNames: ['Gambler', 'Hustler', 'Shark', 'The Bookie', 'Casino Boss', 'The House', 'Syndicate Leader'],
        descKey: 'achievements.theBookie.desc',
        valueLabel: 'wins',
    },
    {
        id: 'nostradamus',
        levelIcons: ICONS,
        levelNames: ['Risky', 'High Roller', 'Visionary', 'Nostradamus', 'Prophet', 'The Matrix', 'Reality Bender'],
        descKey: 'achievements.nostradamus.desc',
        valueLabel: '€ stake',
    },
    {
        id: 'swiss_army_knife',
        levelIcons: ICONS,
        levelNames: ['Handy', 'Utility', 'All-Rounder', 'Swiss Army Knife', 'Jack of All Trades', 'The Maestro', 'Ultimate Weapon'],
        descKey: 'achievements.swissArmyKnife.desc',
        valueLabel: '',
    },
]
